---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # traefik.ingress.kubernetes.io/router.middlewares: nkp-flux-provisioned-phvwv-jjxpb-stripprefixes@kubernetescrd,nkp-flux-provisioned-phvwv-jjxpb-forwardauth-full@kubernetescrd
    cert-manager.io/cluster-issuer: selfsigned-issuer
    cert-manager.io/duration: 2160h # 90 days
    cert-manager.io/renew-before: 360h # 15 days
    traefik.ingress.kubernetes.io/router.tls: "true"
  generation: 1
  labels:
    app: neuvector
  name: neuvector
  namespace: neuvector
spec:
  ingressClassName: kommander-traefik
  rules:
  - http:
      paths:
      - backend:
          service:
            name: neuvector-service-webui
            port:
              number: 8443
        path: /dkp/neuvector
        pathType: Prefix